import type { FileIconConfig } from '@/types';

const iconMap: Record<string, FileIconConfig> = {
  js: { icon: 'fa-file-code', color: '#dcdcaa' },
  jsx: { icon: 'fa-file-code', color: '#4fc1ff' },
  mjs: { icon: 'fa-file-code', color: '#dcdcaa' },
  ts: { icon: 'fa-file-code', color: '#4fc1ff' },
  tsx: { icon: 'fa-file-code', color: '#4fc1ff' },
  html: { icon: 'fa-file-code', color: '#ce9178' },
  htm: { icon: 'fa-file-code', color: '#ce9178' },
  css: { icon: 'fa-file-code', color: '#4ec9b0' },
  scss: { icon: 'fa-file-code', color: '#c586c0' },
  less: { icon: 'fa-file-code', color: '#4ec9b0' },
  json: { icon: 'fa-file-code', color: '#dcdcaa' },
  md: { icon: 'fa-file-lines', color: '#e0e0e0' },
  py: { icon: 'fa-file-code', color: '#4ec9b0' },
  java: { icon: 'fa-file-code', color: '#c586c0' },
  go: { icon: 'fa-file-code', color: '#4fc1ff' },
  rs: { icon: 'fa-file-code', color: '#ce9178' },
  php: { icon: 'fa-file-code', color: '#4ec9b0' },
  rb: { icon: 'fa-file-code', color: '#f44747' },
  sql: { icon: 'fa-file-code', color: '#c586c0' },
  xml: { icon: 'fa-file-code', color: '#e0e0e0' },
  yaml: { icon: 'fa-file-code', color: '#e0e0e0' },
  yml: { icon: 'fa-file-code', color: '#e0e0e0' },
  sh: { icon: 'fa-terminal', color: '#4ec9b0' },
  bash: { icon: 'fa-terminal', color: '#4ec9b0' },
  dockerfile: { icon: 'fa-docker', color: '#4fc1ff' },
  gitignore: { icon: 'fa-git-alt', color: '#f44747' },
  vue: { icon: 'fa-file-code', color: '#4ec9b0' },
  svelte: { icon: 'fa-file-code', color: '#f44747' },
  c: { icon: 'fa-file-code', color: '#4fc1ff' },
  cpp: { icon: 'fa-file-code', color: '#4fc1ff' },
  h: { icon: 'fa-file-code', color: '#4fc1ff' },
  cs: { icon: 'fa-file-code', color: '#c586c0' },
  swift: { icon: 'fa-file-code', color: '#ce9178' },
  kt: { icon: 'fa-file-code', color: '#c586c0' },
  r: { icon: 'fa-file-code', color: '#4fc1ff' },
  dart: { icon: 'fa-file-code', color: '#4fc1ff' },
  lua: { icon: 'fa-file-code', color: '#4fc1ff' },
};

export function getFileIcon(filename: string): FileIconConfig {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  return iconMap[ext] || { icon: 'fa-file', color: '#8a8a8a' };
}

export function getLanguageFromFilename(filename: string): string {
  const extMap: Record<string, string> = {
    js: 'javascript',
    jsx: 'javascript',
    mjs: 'javascript',
    ts: 'typescript',
    tsx: 'typescript',
    html: 'html',
    htm: 'html',
    css: 'css',
    scss: 'scss',
    less: 'less',
    json: 'json',
    md: 'markdown',
    py: 'python',
    java: 'java',
    go: 'go',
    rs: 'rust',
    php: 'php',
    rb: 'ruby',
    sql: 'sql',
    xml: 'xml',
    yaml: 'yaml',
    yml: 'yaml',
    sh: 'shell',
    bash: 'shell',
    vue: 'vue',
    svelte: 'svelte',
    c: 'c',
    cpp: 'cpp',
    h: 'c',
    cs: 'csharp',
    swift: 'swift',
    kt: 'kotlin',
    r: 'r',
    dart: 'dart',
    lua: 'lua',
    dockerfile: 'dockerfile',
  };
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  return extMap[ext] || 'plaintext';
}
