export function registerCodeStudioTheme(monaco: typeof import('monaco-editor')) {
  monaco.editor.defineTheme('codestudio-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6A9955' },
      { token: 'keyword', foreground: 'C586C0' },
      { token: 'identifier', foreground: '9CDCFE' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'regexp', foreground: 'D16969' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'delimiter', foreground: 'D4D4D4' },
      { token: 'tag', foreground: '569CD6' },
      { token: 'attribute.name', foreground: '9CDCFE' },
      { token: 'attribute.value', foreground: 'CE9178' },
      { token: 'meta', foreground: 'D4D4D4' },
    ],
    colors: {
      'editor.background': '#0d0d0d',
      'editor.foreground': '#e0e0e0',
      'editorLineNumber.foreground': '#555555',
      'editorLineNumber.activeForeground': '#8a8a8a',
      'editor.selectionBackground': '#1e3a5f',
      'editor.selectionHighlightBackground': '#2a2a2a',
      'editor.lineHighlightBackground': '#1a1a1a',
      'editor.lineHighlightBorder': '#1a1a1a',
      'editorCursor.foreground': '#4fc1ff',
      'editorWhitespace.foreground': '#333333',
      'editorIndentGuide.background': '#1e1e1e',
      'editorIndentGuide.activeBackground': '#2a2a2a',
      'editor.findMatchBackground': '#2a2a2a',
      'editor.findMatchHighlightBackground': '#1e3a5f',
      'editorGutter.background': '#0d0d0d',
      'editorGutter.modifiedBackground': '#dcdcaa',
      'editorGutter.addedBackground': '#4ec9b0',
      'editorGutter.deletedBackground': '#f44747',
      'editorBracketMatch.background': '#2a2a2a',
      'editorBracketMatch.border': '#4fc1ff',
      'editorOverviewRuler.border': '#2a2a2a',
      'editorWidget.background': '#161616',
      'editorWidget.border': '#2a2a2a',
      'editorSuggestWidget.background': '#161616',
      'editorSuggestWidget.border': '#2a2a2a',
      'editorSuggestWidget.selectedBackground': '#1e3a5f',
      'editorHoverWidget.background': '#161616',
      'editorHoverWidget.border': '#2a2a2a',
    },
  });
}
